# Workflow name
name: 'Base example update'

on:
  push:
    branches: [ main ]
    paths:
      - 'services/api-koa/**'
      - 'services/web/**'
      - 'packages/create-ship-app/**'
      - 'packages/node-mongo/**'
      - 'deploy/digital-ocean/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario'
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Configure git'
        run: |
          git config --global user.email "github-actions"
          git config --global user.name "github-actions@github.com"
      - name: 'Change dir'
        run: |
          cd examples
          rm -rf base
          chmod +x /home/runner/work/autobuild/autobuild/packages/create-ship-app/src/scripts/full-stack.sh
      - name: 'Build base'
        run: /home/runner/work/autobuild/autobuild/packages/create-ship-app/src/scripts/full-stack.sh base /home/runner/work/autobuild/autobuild/packages/create-ship-app/src api-koa docker-compose-koa.yml Koa.js MongoDB digital-ocean/common digital-ocean/koa
        shell: bash
      - name: 'Push changes'
        run: |
          git push origin main
